### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
:smiley:

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
- travis: https://travis-ci.org/AdrieanKhisbe/seneca-web-hapi
- coveralls:  https://coveralls.io/github/AdrieanKhisbe/seneca-web-hapi

**Comment by mirceaalexandru** [comment]
@AdrieanKhisbe Thank You

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Comment by AdrieanKhisbe** [comment]
damn, typo in badge

**Comment by mirceaalexandru** [comment]
I saw that, I will fix it on my next commit

On Fri, Dec 18, 2015 at 2:28 PM, Adrien Becchis notifications@github.com
wrote:

> damn, typo in badge
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mirceaalexandru/seneca-web-hapi/pull/6#issuecomment-165767338
> .

## 

_malex_

**Comment by AdrieanKhisbe** [comment]
haaa. made a PR.
Took the opportunity to add node engine section to `package.json`

**Pull request merged**
